apiVersion: v1
kind: ReplicationController
metadata:
  name: mqtt-chat
  labels:
    name: mqtt-chat
spec:
  replicas: 3
  selector:
    name: mqtt-chat
  template:
    metadata:
      labels:
        name: mqtt-chat
    spec:
      containers:
      - name: mqtt-chat
        image: yuichi1004/mqtt-chat
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

